### ISSUE TITLE
protoc-gen-flowtypes: issue with options

### ISSUE THREAD

**Issue by StK88** [tmc/grpcutils#17]
Hi there,
Some issues with options, I've got these lines on top of my .proto file:

```
option java_package = "xxx.generated";
option java_multiple_files = true;

// For optional types
import "scalapb/scalapb.proto";
import "google/protobuf/wrappers.proto";
option (scalapb.options) = {
  primitive_wrappers: true
};
```

and on running flowtypes_out I get this error:
**--flowtypes_out: proto: missing extension**

If I temporary remove options it generates flow types with I assume warning: **issue getting field options: proto: missing extension**, flow types js file is generated.

The main question, how to get it working with options?
Thanks.

**Comment by gabriel** [comment]
I have a similar issue... if I have 

```
option go_package = "proto";
``` 

in my proto file it fails with 

```
--flowtypes_out: proto: missing extension
```

If I remove the option everything works ok.

**Comment by tmc** [comment]
Sorry I missed this issue. That is definitely a bug.

**Comment by tmc** [comment]
@StK88 thanks for the report. This is now fixed.
