### ISSUE TITLE
protoc-gen-flowtypes: issues with executable and enums

### ISSUE THREAD

**Issue by StK88** [tmc/grpcutils#21]
Hi there, few issues,
1. the `protoc-gen-flowtypes` executable is not built, on `go get github.com/tmc/grpcutil/protoc-gen-flowtypes`
getting an error:
![screenshot_6](https://user-images.githubusercontent.com/5526175/43713173-4c94d652-9981-11e8-92da-bb4d9c7c67fa.png)
removing this pkg from `main.go` fixed the issue.
ref: https://github.com/StK88/grpcutil/commit/29e5305292bef72dbee24790ad854e4d3f051d02
2. enums are not imported in generated files as dependencies
I'm not familiar with `go`, but fixed it with this https://github.com/StK88/grpcutil/commit/f75e473b132cf3be108c1529ae93e68551795647

**Comment by tmc** [comment]
This was fixed in master some time ago.
