### ISSUE TITLE
protoc-gen-tstypes: Ability to ignore optional qualifier

### ISSUE THREAD

**Issue by Kintoun** [tmc/grpcutils#26]
It may be nice to expose a command line argument which treats proto optional keyword (or unspecified in proto3) as if required keyword was specified.

Example Proto:
"optional string test = 1;"
Typescript:
"string: test"
Instead of:
"string?: test"

Reasoning:
My project uses protobufs for in-process communication. The ts'ed types are used directly by the consumer and it is "annoying" to have consumer code always check against undefined when we know it cannot be. Proto3 does not support required keyword (not that we'd use required keyword anyway).

**Comment by tmc** [comment]
I would implement this as a custom option such as in https://github.com/tmc/grpcutil/blob/master/protoc-gen-flowtypes/opts/opts.proto

**Comment by tmc** [comment]
@Kintoun isn't treating optional as required kind of the opposite of what you'd want?

**Comment by Kintoun** [comment]
The end goal is we want the gen ts to be outputting "string: test" instead of "string?: test". For now we're using protoc-gen-tstypes to output the ts files then manually editing them to remove the '?'. It may seem like an odd ask, but as far as I can tell there is no way to have protoc-gen-tstypes not output a '?' on fields.

**Comment by tmc** [comment]
@Kintoun does https://github.com/tmc/grpcutil/pull/27 do what you were intending?

**Comment by Kintoun** [comment]
Yes awesome thanks!

**Comment by tmc** [comment]
Marking closed.
