### ISSUE TITLE
Split files into separate packages

### ISSUE THREAD

**Issue by johanbrandhorst** [tmc/grpcutils#4]
The JWT-PerRPCCredentials struct and the jsonpb marshaler are both neat, but they shouldn't be in the same package. Create some sub packages so that these packages can be vendored and used separately.

**Comment by tmc** [comment]
I agree.

**Comment by tmc** [comment]
https://github.com/tmc/grpcutil/commit/6a58a316041c0a6bbced200226564648a699e967
